{{- if .Values.autoscaling.realtime.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "control.fullname" . }}-realtime
  labels:
    {{- include "control.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "control.fullname" . }}-realtime
  minReplicas: {{ .Values.autoscaling.realtime.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.realtime.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.realtime.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.realtime.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.realtime.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.realtime.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
