apiVersion: v1
kind: Service
metadata:
  name: {{ include "control.fullname" . }}
  labels:
    app: {{ .Values.global.product }}
    tier: server
    chart: {{ include "control.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.control.port }}
      targetPort: {{ .Values.control.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.global.product }}
    tier: server
    chart: {{ include "control.fullname" . }}
    api: "true"
